name: Format Code With CLang
on: 
  push:
    branches:
    - 'master'
jobs:
  format-code:
    runs-on: ubuntu-22.04
    steps:
    - name: Install clang
      run: |
        curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
        sudo dpkg -i libffi6_3.2.1-8_amd64.deb
        wget https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo apt-key add llvm-snapshot.gpg.key
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
        sudo apt update
        sudo apt install clang-format -y
        clang-format --version
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run formatter
      run: |
        ./env/restyle.sh
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic commit with code formatted
