name: Format Code With CLang
on: 
  push:
    beranches:
    - 'master'
jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
    - name: Install clang
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
        sudo apt update
        sudo apt install clang-format-14 -y
        clang-format --version
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run formatter
      run: |
        ./env/restyle.sh
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic commit with code formatted